# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FlashyTableViews' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FlashyTableViews
    pod 'SWTableViewCell', '~> 0.3.7'
    pod 'APParallaxHeader'

  target 'FlashyTableViewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlashyTableViewsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
